#!/usr/bin/env python3
"""Evaluate MA-related v2 strategy candidates generated by Hermes.

- Loads 100 specs from research/strategy_candidates/ma_related_100_specs_*.json unless MA_SPECS_JSON is set.
- Excludes ETFs from the universe.
- Runs xsec + walk-forward validation with the current v2 engine.
- Saves every evaluated candidate to strategies_v2.db and emits JSONL rows.
"""
from __future__ import annotations

import glob
import json
import os
from pathlib import Path

from tradingagents.dataflows.kis_history_store import KisHistoryStore
from tradingagents.hermes.backtest_engine_v2 import run_universe_backtest_v2
from tradingagents.hermes.forward_test import ETF_CODES
from tradingagents.hermes.strategy_research_v2 import _preload
from tradingagents.hermes.strategy_spec import spec_hash
from tradingagents.hermes.strategy_spec_v2 import validate_spec_v2
from tradingagents.hermes.strategy_store_v2 import StrategyStoreV2
from tradingagents.hermes.strategy_validation import engine_version, run_walk_forward_validation

MAX_EVAL = int(os.environ.get("V2_MA_MAX", "100"))
OUT_JSONL = Path(os.environ.get("V2_MA_OUT", "artifacts/strategy_v2_ma_related_100_batch.jsonl"))
BANNED = {"price_drop", "price_return", "realized_vol", "short_ratio"}


def latest_specs_path() -> Path:
    env = os.environ.get("MA_SPECS_JSON")
    if env:
        return Path(env)
    pats = sorted(glob.glob("research/strategy_candidates/ma_related_100_specs_*.json"))
    if not pats:
        raise FileNotFoundError("No ma_related_100_specs_*.json under research/strategy_candidates")
    return Path(pats[-1])


def sig_types(spec: dict) -> set[str]:
    out: set[str] = set()
    for side in ("entry", "exit"):
        obj = spec.get(side, {}) or {}
        for key in ("all_of", "signal_all_of"):
            for sig in obj.get(key, []) or []:
                if isinstance(sig, dict) and "signal" in sig:
                    out.add(sig["signal"])
    return out


def fmt(m: dict) -> str:
    def r(x):
        return "NA" if x is None else f"{x:.4g}" if isinstance(x, float) else str(x)
    return f"sh={r(m.get('sharpe'))} ex={r(m.get('excess_sharpe'))} mdd={r(m.get('mdd_pct'))} n={m.get('n_trades')} cum={r(m.get('cum_return_pct'))}"


def load_candidates(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    specs = data.get("specs") or []
    out = []
    seen = set()
    for s in specs:
        # generation note is metadata, not part of canonical strategy spec
        s = {k: v for k, v in s.items() if k != "note"}
        validate_spec_v2(s)
        st = sig_types(s)
        if st & BANNED:
            raise ValueError(f"banned signal in {s.get('name')}: {st & BANNED}")
        h = spec_hash(s)
        if h not in seen:
            seen.add(h)
            out.append(s)
    return out


def main() -> int:
    specs_path = latest_specs_path()
    candidates = load_candidates(specs_path)
    store = StrategyStoreV2()
    with store._conn() as c:
        before_total, before_pass, before_max = c.execute(
            "SELECT count(*), coalesce(sum(gate_passed),0), coalesce(max(id),0) FROM strategies"
        ).fetchone()
        existing = {r[0] for r in c.execute("SELECT spec_hash FROM strategies")}

    etf_codes = set(str(x)[:6] for x in ETF_CODES)
    raw = [tk for tk in KisHistoryStore().list_tickers() if str(tk)[:6] not in etf_codes]
    print(f"[ma-100] specs={specs_path} total_specs={len(candidates)} before total={before_total} max_id={before_max} passed={before_pass} raw={len(raw)} ETF-excluded", flush=True)
    tickers, loader, kf, uf = _preload(raw)
    specs = [s for s in candidates if spec_hash(s) not in existing]
    print(f"[ma-100] universe={len(tickers)} candidates_new={len(specs)} max={MAX_EVAL} engine={engine_version()} banned={sorted(BANNED)}", flush=True)

    OUT_JSONL.parent.mkdir(parents=True, exist_ok=True)
    evaluated = 0
    passed: list[dict] = []
    best = None
    with OUT_JSONL.open("a", encoding="utf-8") as out:
        for spec in specs:
            if evaluated >= MAX_EVAL:
                break
            xsec = run_universe_backtest_v2(spec, tickers, loader=loader, kospi_fetcher=kf, usdkrw_fetcher=uf)
            wf = run_walk_forward_validation(spec, tickers, loader=loader, kospi_fetcher=kf, usdkrw_fetcher=uf)
            sid, is_new = store.save(spec, xsec, name=spec["name"], wf_result=wf, engine_version=engine_version())
            evaluated += 1
            row = {
                "strategy_id": sid,
                "is_new": is_new,
                "name": spec["name"],
                "gate_passed": bool(wf["gate_passed"]),
                "wf_excess_ir_median": wf.get("oos_excess_ir_median"),
                "wf_excess_ir_min": wf.get("oos_excess_ir_min"),
                "wf_oos_sharpe_median": wf.get("oos_sharpe_median"),
                "xsec_in": xsec["in_sample"],
                "xsec_out": xsec["out_sample"],
            }
            out.write(json.dumps(row, ensure_ascii=False) + "\n")
            out.flush()
            key = (
                row["wf_excess_ir_min"] if row["wf_excess_ir_min"] is not None else -999,
                row["wf_excess_ir_median"] if row["wf_excess_ir_median"] is not None else -999,
            )
            if best is None or key > best[0]:
                best = (key, row)
            if row["gate_passed"]:
                passed.append(row)
            flag = "PASS" if row["gate_passed"] else "    "
            print(f"[{evaluated:03}/{MAX_EVAL}] {flag} #{sid} {spec['name'][:72]:72} wf_med={row['wf_excess_ir_median']} wf_min={row['wf_excess_ir_min']} | in {fmt(xsec['in_sample'])} out {fmt(xsec['out_sample'])}", flush=True)

    with store._conn() as c:
        after_total, after_pass, after_max = c.execute(
            "SELECT count(*), coalesce(sum(gate_passed),0), coalesce(max(id),0) FROM strategies"
        ).fetchone()
    print(f"[ma-100] done evaluated={evaluated} new_rows={after_total-before_total} id={before_max+1}..{after_max} passed_delta={after_pass-before_pass} out={OUT_JSONL}", flush=True)
    if passed:
        print("[ma-100] PASSED_TOP " + json.dumps(passed[:10], ensure_ascii=False)[:12000], flush=True)
    if best:
        print("[ma-100] BEST " + json.dumps(best[1], ensure_ascii=False)[:6000], flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
